application: daily-stock-forecast
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /bower_components
  static_dir: bower_components

- url: /components
  static_dir: components

- url: /post-service
  static_dir: post-service

- url: /api
  static_dir: api

- url: /oldImages
  static_dir: oldImages

- url: /jquery-ui-1.11.2
  static_dir: jquery-ui-1.11.2

- url: /images
  static_dir: images

- url: /testData
  script: testData.application

- url: /forecast
  script: forecast.app
  login: admin

- url: /oauth2callback
  script: forecast.app

- url: /cleards
  script: cleards.app
  login: admin

- url: /symbol/(.*)
  script: dailystockquant.app

- url: /markets
  script: dailystockquant.app

- url: /.*
  script: dailystockquant.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
# [END libraries]
